[package]
name = "fraction"
version = "0.2.0"
authors = ["dnsl48 <dnsl48@gmail.com>"]

description = "Lossless floats that may be used in matching, ordering and hashing"
keywords = ["fraction"]

license = "MIT/Apache-2.0"

homepage = "https://github.com/dnsl48/fraction.git"
repository = "https://github.com/dnsl48/fraction.git"
# documentation = "https://github.com/dnsl48/fraction/wiki"
readme = "README.md"


[dependencies]


[dependencies.num]
version = "0.1.34"
default-features = false
features = ["bigint", "rational"]